version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3002
  nginx-app:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 3001:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
  